services:
  - type: web
    name: hoja-vida-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USE_SSL
        value: "false"
      - key: RECIPIENT_EMAIL
        value: euler.chapid.it@gmail.com
      - key: PUBLIC_EMAIL
        value: euler.chapid.it@gmail.com
      - key: CV_FILE_PATH
        value: hoja de vida 2026a.pdf
